# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bad27e7210177df28e59515d788dc78556f14f8e77812272a6fe7c45ba35041a37f94b47b715455acf46c9c824de0958f8a2be45d5d2d385cfcbf9001f4d7c0

test:
  secret_key_base: 35db9a3d12f53daf57d37c2de5c3b51a5578203e37a5d54f1402b3a7bfe0b06108447af7bf322af04d730d685f45b6d487729cfb611dff422189d30911df5e63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
